version: "3.8"

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: friendship
    ports:
      - "3306:3306"

  api:
    build: .
    ports:
      - "8081:8080"
    depends_on:
      - db
    environment:
      - MYSQL_DSN=root:password@tcp(db:3306)/friendship?charset=utf8mb4&parseTime=True&loc=Local
